# Generated by Django 5.1.3 on 2025-12-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_add_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="attachments",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="email",
            name="links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="email",
            name="sender_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
