# Generated by Django 5.1.3 on 2026-02-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_email_attachments_email_links_email_sender_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="sender",
        ),
        migrations.AddField(
            model_name="email",
            name="sender_email",
            field=models.EmailField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="email",
            name="sender_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="email",
            name="subject",
            field=models.CharField(default="", max_length=255),
        ),
    ]
