# Generated by Django 5.1.3 on 2026-02-06 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_interactionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=255)),
                ('sector', models.CharField(default='', max_length=255)),
                ('role_title', models.CharField(default='', max_length=255)),
                ('department_name', models.CharField(default='', max_length=255)),
                ('line_manager_name', models.CharField(default='', max_length=255)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('intro_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='mode',
            field=models.CharField(choices=[('arcade', 'Arcade'), ('simulation', 'Simulation')], default='arcade', max_length=20),
        ),
        migrations.AddField(
            model_name='email',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='api.scenario'),
        ),
    ]
