# Generated by Django 5.1.3 on 2026-02-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_scenario_email_mode_email_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='level_number',
            field=models.IntegerField(default=1),
        ),
    ]
