# Generated by Django 5.1.3 on 2026-02-09 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_email_level_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(default='', max_length=255)),
                ('briefing', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='api.scenario')),
            ],
            options={
                'ordering': ['scenario_id', 'number'],
                'unique_together': {('scenario', 'number')},
            },
        ),
        migrations.CreateModel(
            name='LevelEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_levels', to='api.email')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_emails', to='api.level')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('level', 'email')},
            },
        ),
    ]
