# Generated by Django 5.1.3 on 2026-02-11 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_level_levelemail"),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                (
                    "mode",
                    models.CharField(
                        choices=[("arcade", "Arcade"), ("simulation", "Simulation")],
                        default="simulation",
                        max_length=20,
                    ),
                ),
                ("level_number", models.IntegerField(default=1)),
                ("emails_total", models.IntegerField(default=0)),
                ("correct", models.IntegerField(default=0)),
                ("incorrect", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="api.level",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="api.scenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailDecisionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("report_phish", "Report Phish"),
                            ("mark_read", "Mark as Read"),
                            ("mark_safe", "Mark Safe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("was_correct", models.BooleanField(default=False)),
                ("had_link_click", models.BooleanField(default=False)),
                ("had_attachment_open", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="api.email",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions",
                        to="api.levelrun",
                    ),
                ),
            ],
        ),
    ]
