# Generated by Django 5.1.3 on 2026-02-17 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_levelrun_emaildecisionevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='level_number',
        ),
    ]
