# Generated by Django 5.1.3 on 2026-02-20 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_email_level_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcadeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('difficulty_float', models.FloatField(default=2.0)),
                ('streak', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.email')),
            ],
        ),
        migrations.CreateModel(
            name='ArcadeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('guess_is_phish', models.BooleanField()),
                ('was_correct', models.BooleanField()),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('target_difficulty', models.FloatField()),
                ('email_difficulty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.email')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='api_arcadea_user_id_719641_idx'), models.Index(fields=['user_id', 'email'], name='api_arcadea_user_id_614650_idx')],
            },
        ),
    ]
