# Generated by Django 5.1.3 on 2026-02-25 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_arcadestate_arcadeattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PvpLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('briefing', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('unlisted', 'Unlisted'), ('posted', 'Posted')], default='unlisted', max_length=20)),
                ('plays', models.IntegerField(default=0)),
                ('avg_accuracy', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvp_levels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PvpEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='', max_length=255)),
                ('sender_email', models.EmailField(default='', max_length=255)),
                ('subject', models.CharField(default='', max_length=255)),
                ('body', models.TextField()),
                ('is_phish', models.BooleanField(default=False)),
                ('difficulty', models.IntegerField(default=1)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('links', models.JSONField(blank=True, default=list)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_wave', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='api.pvplevel')),
            ],
            options={
                'ordering': ['is_wave', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PvpScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(default='', max_length=255)),
                ('sector', models.CharField(default='', max_length=255)),
                ('role_title', models.CharField(default='', max_length=255)),
                ('department_name', models.CharField(default='', max_length=255)),
                ('line_manager_name', models.CharField(default='', max_length=255)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('intro_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvp_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pvplevel',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='api.pvpscenario'),
        ),
    ]
