# Generated by Django 5.1.3 on 2026-03-01 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_pvplevel_pvpemail_pvpscenario_pvplevel_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='pvp_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_shadow', to='api.pvplevel'),
        ),
        migrations.AddField(
            model_name='pvpemail',
            name='shadow_email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pvp_source', to='api.email'),
        ),
        migrations.AlterField(
            model_name='email',
            name='mode',
            field=models.CharField(choices=[('arcade', 'Arcade'), ('simulation', 'Simulation'), ('pvp', 'PVP')], default='arcade', max_length=20),
        ),
    ]
