# Generated by Django 5.1.3 on 2026-03-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_email_pvp_level_pvpemail_shadow_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='scenario_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
