# Generated by Django 5.1.3 on 2026-03-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_level_scenario_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelrun',
            name='client_duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='levelrun',
            name='duration_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levelrun',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
