# Generated by Django 5.1.3 on 2026-03-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_levelrun_client_duration_ms_levelrun_duration_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelrun',
            name='mode',
            field=models.CharField(choices=[('arcade', 'Arcade'), ('simulation', 'Simulation'), ('pvp', 'PVP')], default='simulation', max_length=20),
        ),
    ]
