# Generated by Django 5.1.3 on 2026-03-07 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_levelrun_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelrun',
            name='pvp_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='api.pvplevel'),
        ),
    ]
